{
 "title": "Netprobe",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "## Internet Quality Score\nThe Internet Quality Score is a calculated metric designed to provide you an idea of your inernet quality at any given time. This score is rated between 0 and 100, and measures the quality of your internet connection based on four metrics:\n\n- Packet loss\n- Latency\n- Jitter\n- DNS Response Times\n"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "## DNS Response Time\nDNS is the protocol used to turn website names into IP addresses. Almost every request to the internet starts with a DNS request. This graph shows the response time of your currently configured DNS server, as well as several popular public DNS servers. Your own DNS response time should be close to that of these public providers. Slow DNS response could be caused by:\n\n- Poor DNS server performance\n- High latency"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "## Packet Loss\nThe % of packets (messages) that are lost when being transmitted over your internet connection. Packet loss should be 0% consistently with occasional spikes during peak home internet use. When internet use is low and packet loss persists, it could indicate:\n\n- Faulty internal hardware (including cabling or modem)\n- Faulty ISP hardware\n- ISP capacity problems\n"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 0 },
   "options": {
    "content": "## Jitter\nJitter is the rate of change of your latency, or put simply how frequently your latency is changing. High jitter in the red zone can have a negative impact on real-time streaming applications, such as voice or video calls. Jitter is typically higher when you are at peak utilizaiton. Consistently high jitter could be caused due to:\n\n- Faulty internal hardware (including cabling or modem)\n- Faulty ISP hardware\n- Overuse of current internet capacity (hitting the limit)"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Internet Quality Score (Avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Health_Stats * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Response Time (My DNS Server)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DNS_Stats{server=\"My_DNS_Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss (Avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"loss\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter (Avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"jitter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "Health_Stats * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "DNS_Stats", "legendFormat": "{{server}}" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"loss\"}",
     "legendFormat": "Packet loss"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"jitter\"}",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Latency to Anchors (Avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 20 },
   "options": {
    "content": "## Latency to Anchors\nThe round trip time between the probe and several high-profile target websites, averaged. Latency is usually a function of distance between your site and the destinations. Higher latency means slower performance, even on a high speed connection. If your latency is in the red zone consistently, there could be several causes including:\n\n- Faulty internal hardware (including cabling or modem)\n- Faulty ISP hardware\n- ISP routing issue"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Network_Stats{type=\"latency\"}",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}